// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // The Windows desktop app is registered as a Firebase web app; the web
      // build (used for emulator-based UI testing) shares that config.
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAijxJoKjuMdXk87mFqIDcbARxY5etQv8',
    appId: '1:212546816206:android:bcc5b9d97cece66be7a89f',
    messagingSenderId: '212546816206',
    projectId: 'alfardos-mgmt',
    storageBucket: 'alfardos-mgmt.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBF6AaM2oWZ_coeaD6XW8CRUWpCejf8hs',
    appId: '1:212546816206:web:46a8e10279141384e7a89f',
    messagingSenderId: '212546816206',
    projectId: 'alfardos-mgmt',
    authDomain: 'alfardos-mgmt.firebaseapp.com',
    storageBucket: 'alfardos-mgmt.firebasestorage.app',
  );
}
